# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='distrito',
            unique_together=set([('nombre', 'provincia')]),
        ),
        migrations.AlterUniqueTogether(
            name='provincia',
            unique_together=set([('nombre', 'departamento')]),
        ),
    ]
